package wacc.error

import wacc.syntax.*

/** Error data structure that holds information about the error.
  * 
  * Used by the syntactic and semantic analysis phases to generate structured errors.
  */
trait ErrorItem

/** Types of errors that can be generated by the frontend. */
enum ErrorLines {
    /** Default error. */
    case VanillaError(unexpected: Option[ErrorItem], expected: Set[ErrorItem], reasons: Set[String], line: Seq[String])
    /** Specialised error. */
    case SpecialisedError(msgs: Set[String], line: Seq[String])
}

/** Contains the main error data structures used by the frontend. */
object errors {
    /** Describes the shared structure of printing all errors. */
    sealed trait WaccError(pos: bridges.Position, source: String, lines: ErrorLines) {
        val errorType: String

        override def toString(): String = {
            val sb = new StringBuilder

            sb.append(s"$errorType in $source at position (${pos._1}, ${pos._2}):")
            lines match {
                case ErrorLines.VanillaError(unexpected, expected, reasons, line) =>
                    sb.append(s"\n  unexpected: ${unexpected.getOrElse("end of input")}")
                    sb.append(s"\n  expected: ${expected.mkString(", ")}")
                    if (reasons.nonEmpty) {
                        sb.append(s"\n  reasons: ${reasons.mkString(", ")}")
                    }
                    sb.append(s"\n  ${line.mkString("\n  ")}")
                
                case ErrorLines.SpecialisedError(msgs, line) =>
                    sb.append(s"\n  ${msgs.mkString(", ")}")
                    sb.append(s"\n  ${line.mkString("\n  ")}")
            }

            sb.toString()
        }
    }

    /** Error that occurs during the syntactic analysis phase. */
    case class SyntaxError(pos: bridges.Position, source: String, lines: ErrorLines) extends WaccError(pos, source, lines) {
        override val errorType: String = "Syntax Error"
    }
    /** Error that occurs during the semantic analysis phase. */
    case class SemanticError(pos: bridges.Position, source: String, lines: ErrorLines, errTy: String) extends WaccError(pos, source, lines) {
        override val errorType: String = errTy
    }
    /** Error that occurs during the file reading phase. */
    case object FileNotFound extends WaccError((0, 0), "", ErrorLines.VanillaError(None, Set.empty, Set.empty, Seq.empty)) {
        override val errorType: String = "File Not Found"
    }
}

/** Builder object for generating error messages.
  * 
  * Contains common methods for generating error messages.
  */ 
object WaccErrorBuilder {
    /** Default parameters of the error message. */
    final val ErrorLineStart = "|"
    final val NumLinesBefore = 1
    final val NumLinesAfter = 1

    /** Generates the code segment where the error occurred. */
    def lineInfo(line: String, linesBefore: Seq[String], linesAfter: Seq[String], lineNum: Int, errorPointsAt: Int, errorWidth: Int): Seq[String] = {
        Seq.concat(
            linesBefore.map(inputLine(_, lineNum - 1)),
            Seq(inputLine(line, lineNum), caretLine(errorPointsAt, errorWidth)),
            linesAfter.map(inputLine(_, lineNum + 1)),
        )
    }

    /** Adds line number information to the code segment. */
    def inputLine(line: String, lineNum: Int): String = s"$lineNum: $ErrorLineStart$line"

    /** Adds caret information to the code segment. */
    def caretLine(caretAt: Int, caretWidth: Int): String = s"${" " * (ErrorLineStart.length + caretAt)}${"^" * caretWidth}"
}
